games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

urlpatterns = [
    path('', views.index, name='index'),
    path('postings/', views.posting_list, name='posting_list'),
    path('posting/create/', views.posting_create, name='posting_create'),
    path('posting/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('posting/<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('posting/<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    path('posting/<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

postings/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Posting(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='postings', null=True, blank=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comment_list')
    content = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    
    def __str__(self):
        if len(self.content) <= 10:
            return f'{self.posting.title} - {self.content}'
        else:
            return f'{self.posting.title} - {self.content[:10]}...'

postings/forms.py
from django import forms
from .models import Posting, Comment

class PostingForm(forms.ModelForm):
    title = forms.CharField(label='제목', max_length=50)
    content = forms.CharField(label='내용', strip=False, widget=forms.Textarea)

    class Meta:
        model = Posting
        fields = ['title', 'content',]

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', max_length=300, strip=False, widget=forms.Textarea(attrs={'rows':2}))

    class Meta:
        model = Comment
        fields = ['content',]

postings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment
from .forms import PostingForm, CommentForm
# [코드 작성] django.contrib.auth.decorators 에서 login_required 데코레이션 가져오기

# [코드 작성] django.views.decorators.http 에서 require_POST 데코레이션 가져오기

# Paginator 가져오기
from django.core.paginator import Paginator
# get_user_model 가져오기
from django.contrib.auth import get_user_model

# Create your views here.
def default_posting():
    None
#def default_posting():
    # 포스팅 객체가 하나도 경우
    #if Posting.objects.all().count() == 0:
        # (admin 계정이 있다는 가정하에) admin 유저 불러오기
        # [코드 수정] createsuperuser시 사용자 이름을 admin으로 만들지 않았다면 'admin' 대신 본인 계정의 username을 문자열로 넣어주기
        #user_admin = get_object_or_404(get_user_model(), username='admin')
        # 작성자가 admin인 게시글 300개 생성
        #for i in range(1, 301):
            #Posting.objects.create(
                #title = f'연습용 데이터({i})입니다.',
                #content = f'{i}번 글입니다.',
                #author = user_admin
            #)

def index(request):
    default_posting()
    return render(request, 'postings/index.html')

def posting_list(request):
    # [코드 수정] 페이지네이션
    # Posting 객체들을 'date'기준으로 역순으로 정렬
    postings = Posting.objects.order_by('date').reverse()
    # 정렬된 postings의 전체 개수 저장
    postings_num = postings.count()

    # Paginator를 이용하여 postings 객체를 10개씩 가져오기
    paginator = Paginator(postings, 10)
    # GET 방식으로 url중 ?page의 value값을 받아옴
    page = request.GET.get('page')
    # page가 선택되지 않았을 경우에는 '1'로 설정
    if page == None:
        page = '1'
    # 존재하지 않는 경로로 접근하는 경우 404 페이지로 반환
    elif page == '0' or not page.isdecimal():
        return render(request, '404.html')

    # 화면에 보여질 페이지 개수 설정
    count = 5
    # 현재 보여지는 페이지를 정수형으로 변환
    recent_page = int(page)
    # 현재 페이지의 글 개수
    recent_page_count = 10
    
    # 마지막 페이지 번호 계산
    last_page = postings_num // 10
    if postings_num % 10 != 0:
        last_page += 1
    # 현재 페이지의 글 개수 계산
    if recent_page == last_page:
        recent_page_count = postings_num % 10
    # 마지막 페이지보다 큰 숫자로 접근하는 경우 404 페이지로 반환
    elif recent_page > last_page:
        return render(request, '404.html')
    
    # '이전' 버튼을 눌렀을 때 이동할 페이지 번호 계산
    previous_page = ((recent_page-1)//count)*count
    # '이전' 버튼을 눌렀을 때 이동 가능 여부 저장
    move_previous = True
    if previous_page < count:
        move_previous = False
    
    # '다음' 버튼을 눌렀을 때 이동할 페이지 번호 계산
    next_page = ((recent_page-1)//count+1)*count+1
    # '다음' 버튼을 눌렀을 때 이동 가능 여부 저장
    move_next = True
    if next_page > last_page:
        move_next = False
    
    # 현재 페이지에서 이동 가능한 첫 페이지 번호 계산
    start_page = previous_page+1
    # 현재 페이지에서 이동 가능한 마지막 페이지 번호 계산
    end_page = next_page-1
    if end_page > last_page:
        end_page = last_page

    # 현재 페이지에서 이동 가능한 페이지 범위를 리스트로 저장
    page_range = list(range(start_page, end_page+1))
    # page에 해당하는 글 10개 저장
    page_postings = paginator.get_page(page)

    # 현재 페이지에서 보여지는 첫 번째 게시글 번호 저장
    page_postings_start_index = postings_num-(recent_page-1)*10
    print(recent_page_count)

    context = {
        'recent_page_count': recent_page_count*-1,
        'last_page': last_page,
        'previous_page': previous_page,
        'move_previous': move_previous,
        'next_page': next_page,
        'move_next': move_next,
        'start_page': start_page,
        'end_page': end_page,
        'page_range': page_range,
        'page_postings': page_postings,
        'page_postings_start_index': page_postings_start_index,
    }
    return render(request, 'postings/posting_list.html', context)

def posting_create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            posting_form = PostingForm(request.POST)
            
            if posting_form.is_valid():
                posting_form = posting_form.save(commit=False)
                posting_form.author = request.user
                posting_form.save()
                return redirect('postings:posting_list')
        else:
            posting_form = PostingForm()
        
        context = {
            'posting_type': '글쓰기',
            'posting_form': posting_form,
        }
        return render(request, 'postings/posting_form.html', context)
    return redirect('accounts:login')

def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.posting = posting
            comment_form.author = request.user
            comment_form.save()
            return redirect('postings:posting_detail', posting_id)
    else :
        comment_form = CommentForm()
    
    comments = posting.comment_list.all()

    context = {
        'posting': posting,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'postings/posting_detail.html', context)

# [코드 작성] login_required 데코레이션 추가

def posting_update(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if posting.author == request.user:
        if request.method == 'POST':
            posting_form = PostingForm(request.POST, instance=posting)

            if posting_form.is_valid():
                posting_form.save()
                return redirect('postings:posting_detail', posting_id)
        else:
            posting_form = PostingForm(instance=posting)

        context = {
            'posting_type': '글수정',
            'posting': posting,
            'posting_form': posting_form,
        }
        return render(request, 'postings/posting_form.html', context)
    return redirect('postings:posting_detail', posting_id)

# [코드 작성] login_required 데코레이션 추가

# [코드 작성] require_POST 데코레이션 추가

def posting_delete(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    # [미션] 글(posting) 작성자(author)가 로그인한 사람(request.user)과 같을 경우에만 글 삭제가 가능하도록 조건문 작성
    # [미션] True를 지우고 작성
    if posting.author == request.user:
        posting.delete()
        return redirect('postings:posting_list')
    # [미션] posting_id에 해당하는 페이지로 redirect
    return redirect('postings:posting_detail', posting_id)

# [코드 작성] login_required 데코레이션 추가

# [코드 작성] require_POST 데코레이션 추가

def comment_delete(request, posting_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    # [미션] 댓글(comment) 작성자(author)가 로그인한 사람(request.user)과 같을 경우에만 댓글 삭제가 가능하도록 조건문 작성
    # [미션] True를 지우고 작성
    if comment.author == request.user:
        comment.delete()
    return redirect('postings:posting_detail', posting_id)

postings/templates/postings/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/index.css' %}">
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>
  
  <p>이 사이트에는 뭐 별거 없습니다.</p>
  <p>별거 없습니다.</p>
  
  <!-- 이미지 예시 ('static/images/' 안쪽의 사진 불러오기) -->
{% endblock %}

postings/templates/postings/posting_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_detail.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <div class="posting">
    <table class="posting__detail">
      <tr>
        <td class="posting__detail__title">{{posting.title}}</td>
      </tr>
      <tr>
        <td class="posting__detail__date">작성자: {{posting.author.username}}&nbsp;&nbsp;&nbsp;<span class="division">|</span>&nbsp;&nbsp;&nbsp;작성일 : {{posting.date|date:'Y-m-d A f'}}</td>
      </tr>
      <tr>
        <td class="posting__detail__content">
          <div class="content">
            <span class="content__space">{{posting.content|linebreaksbr}}</span>
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__function transparent">
          <div>
            {% if posting.author.username == user.username %}
              <a class="button" href="{% url 'postings:posting_update' posting.id %}">수정</a>
              <form action="{% url 'postings:posting_delete' posting.id %}" method="post" onsubmit="return contentDelete()">
                {% csrf_token %}
                <input class="button" type="submit" value="삭제">
              </form>
            {% endif %}
            <a class="button" href="{% url 'postings:posting_list' %}">글 목록</a>
          </div>
        </td>
      </tr>
    </table>

    <table class="posting__comment">
      <tr>
        <th>댓글 목록</th>
      </tr>
      {% if user.is_authenticated %}
        <tr>
          <td class="posting__comment__create">
            <form action="" method="post">
              {% csrf_token %}
              <div>
                {{comment_form.as_div}}
                <input class="button" type="submit" value="작성">
              </div>
            </form>
          </td>
        </tr>
      {% endif %}
      {% for comment in comments %}
        <tr>
          <td class="posting__comment__content">
            <div>
              <span class="content__space">{{comment.content|linebreaksbr}}</span>
              <div class="posting__comment__delete">
                {% if comment.author.username == user.username %}
                  <form action="{% url 'postings:comment_delete' posting_id=posting.id comment_id=comment.id %}" method="post" onsubmit="return contentDelete()">
                    {% csrf_token %}
                    <input type="submit" value="x">
                  </form>
                {% endif %}
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date">
            {{comment.author.username}}&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;{{comment.date|date:'Y-m-d A f'}}
          </td>
        </tr>
        <tr>
          <td>
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="posting__comment__content">
            댓글이 아직 작성되지 않았습니다.
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date"></td>
        </tr>
        <tr>
          <td>
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <script>
    const contents = document.getElementsByClassName("content__space")
    
    for (let i=0; i<contents.length; i++) {
      contents[i].innerHTML = contents[i].innerHTML.replace(/ /g, "&nbsp;");
    }

    function contentDelete() {
      const result = confirm("삭제하시겠습니까?");
      return result;
    }
  </script>
{% endblock %}

postings/templates/postings/posting_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_form.css' %}">
{% endblock %}

{% block body %}
  <h1>{{posting_type}}</h1>

  <div class="posting-form">
    <form action="" method="post">
      {% csrf_token %}
      {{posting_form.as_p}}
  
      <div class="posting-form__function--bottom">
        {% if posting %}
          <a class="button" href="{% url 'postings:posting_detail' posting.id %}">취소</a>
        {% endif %}
        <input class="button" type="submit" value="등록">
      </div>
    </form>
  </div>
{% endblock %}

postings/templates/postings/posting_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_list.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="posting">
    <div class="posting__function--top">
      <a class="button" href="{% url 'postings:posting_create' %}">글쓰기</a>
    </div>
  
    <table class="posting__list">
      <tr>
        <th class="index">번호</th>
        <th class="title">제목</th>
        <th class="author">작성자</th>
        <th class="date">날짜</th>
      </tr>
      {% for posting in page_postings %}
        <tr>
          <td class="index">{{page_postings_start_index|add:-10|add:forloop.revcounter}}</td>
          <td class="title"><a href="{% url 'postings:posting_detail' posting.id %}">{{posting.title}}</a></td>
          <td class="author">{{posting.author.username}}</td>
          <td class="date">{{posting.date|date:'Y-m-d'}}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="index">-</td>
          <td class="title">글을 작성해주세요.</td>
          <td class="author">-</td>
          <td class="date">-</td>
        </tr>
      {% endfor %}
    </table>

    {% if page_postings %}
      <p class="paginator">
        {% if page_postings.number == 1 %}
          <a class="paginator__disabled" disabled>처음</a>
        {% else %}
          <a href="?page=1">처음</a>
        {% endif %}

        {% if move_previous %}
          <a href="?page={{previous_page}}">이전</a>
        {% else %}
          <a class="paginator__disabled" disabled>이전</a>
        {% endif %}

        {% for page_number in page_range %}
          {% if page_number == page_postings.number %}
            <a class="page_number__active" href="?page={{page_number}}">{{page_number}}</a>
          {% else %}
            <a class="page_number" href="?page={{page_number}}">{{page_number}}</a>
          {% endif %}
        {% endfor %}

        {% if move_next %}
          <a href="?page={{next_page}}">다음</a>
        {% else %}
          <a class="paginator__disabled" disabled>다음</a>
        {% endif %}

        {% if page_postings.number == page_postings.paginator.num_pages %}
          <a class="paginator__disabled" disabled>끝</a>
        {% else %}
          <a href="?page={{page_postings.paginator.num_pages}}">끝</a>
        {% endif %}
      </p>
    {% endif %}
  </div>
{% endblock %}