games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

games/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# [미션] 자유롭게 코드 작성
# [미션] 필요한 필드가 있다면 추가하기
class Weapon(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()

    def __str__(self):
        return self.name

class Character(models.Model):
    nickname = models.CharField(max_length=20)
    weapon = models.ForeignKey(Weapon, on_delete=models.CASCADE, related_name='character_list', null=True, blank=True)
    coin = models.BigIntegerField(default = 0)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='character', null=True, blank=True)

    def __str__(self):
        return self.nickname

class Enemy(models.Model):
    name = models.CharField(max_length=20)
    hp = models.IntegerField()

    def __str__(self):
        return self.name

games/forms.py
from django import forms
from .models import Weapon, Character

class WeaponForm(forms.ModelForm):
    name = forms.CharField(label='무기 이름')
    power = forms.IntegerField(label='무기 공격력', max_value=50)

    class Meta:
        model = Weapon
        fields = '__all__'

class CharacterForm(forms.ModelForm):
    nickname = forms.CharField(label="닉네임을 입력해주세요")

    class Meta:
        model = Character
        fields = ['nickname',]

games/views.py
from django.shortcuts import render, redirect, get_object_or_404
from random import *
from .models import Weapon, Character, Enemy
from .forms import WeaponForm, CharacterForm
# [미션] 자유롭게 코드 작성
# [미션] 코드에 필요한 모듈 불러오기


# Create your views here.
win = 0
draw = 0
lose = 0

# 무기 생성 함수
def weapon_generate():
    # 추가하고 싶은 무기가 있다면 추가 가능
    # weapons 딕셔너리의 key 값은 무기 이름, value 값은 무기 공격력
    weapons = {
        '주먹도끼': 2,
        '가벼운 물총': 3,
        '낡은 검': 5,
        '수상한 막대기': 7,
        '수학의 정석': 9,
    }
    # weapon_name에는 weapons 딕셔너리의 key 값이 저장됨
    for weapon_name in weapons:
        # weapon_name에 해당하는 무기가 없는 경우 새로운 Weapon 객체 생성
        if Weapon.objects.filter(name=weapon_name).count() == 0:
            Weapon.objects.create(
                name = weapon_name,
                power = weapons[weapon_name],
            )

# 적 생성 함수
def enemy_generate():
    # 추가하고 싶은 적이 있다면 추가 가능
    # enemies 딕셔너리의 key 값은 적 이름, value 값은 적 hp
    enemies = {
        '은신 통': 27,
        '매우 작은 슬라임': 1,
        '작은 슬라임': 3,
        '약간 큰 슬라임': 7,
        '큰 슬라임': 10,
        '매우 큰 슬라임': 20,
        '흩날리는 종이': 10,
        '뒤집어진 냄비': 25,
        '수수한 독버섯': 50,
        '수학 공식': 85,
        '아기 용': 100,
        '슈퍼 마왕': 1000,
        '좀비': 50,
        '공허의 보스': 500,
        "''": 10000,
        '말도 안되게 쎈 최강 보스': 50000,
    }
    # enemy_name에는 enemies 딕셔너리의 key 값이 저장됨
    for enemy_name in enemies:
        # enemy_name에 해당하는 적이 없는 경우 새로운 Enemy 객체 생성
        if Enemy.objects.filter(name=enemy_name).count() == 0:
            Enemy.objects.create(
                name = enemy_name,
                hp = enemies[enemy_name],
            )

def game_list(request):
    # 무기를 생성할 필요가 없는 경우 weapon_generate() 함수를 주석으로 달아놓기
    weapon_generate()
    # 적을 생성할 필요가 없는 경우 enemy_generate() 함수를 주석으로 달아놓기
    enemy_generate()
    return render(request, 'games/game_list.html')

def rsp_select(request):
    global win, draw, lose
    context = {
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'games/rsp_select.html', context)

def rsp_result(request, pick):
    global win, draw, lose
    rsp = ['가위', '바위', '보']
    com = choice(rsp)

    if pick == com:
        result = '무승부'
        draw += 1
    elif (pick == '가위' and com == '보') or (pick == '바위' and com == '가위') or (pick == '보' and com == '바위'):
        result = '승리'
        win += 1
    else :
        result = '패배'
        lose += 1

    context = {
        'pick': pick,
        'com': com,
        'result': result,
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'games/rsp_result.html', context)

def rsp_reset(request):
    global win, draw, lose
    win, draw, lose = 0, 0, 0
    return redirect('games:rsp_select')

def weapon_create(request):
    if request.method == 'POST':
        weapon_form = WeaponForm(request.POST)
        
        if weapon_form.is_valid():
            weapon_form.save()
            return redirect('games:weapon_list')
    else:
        weapon_form = WeaponForm()
    
    context = {
        'weapon_form': weapon_form,
    }
    return render(request, 'games/weapon_form.html', context)

def weapon_list(request):
    weapons = Weapon.objects.all()
    context = {
        'weapons': weapons,
    }
    return render(request, 'games/weapon_list.html', context)

def adventure_home(request):
    # 로그인 한 경우
    if request.user.is_authenticated:
        # 생성한 캐릭터가 없을 경우
        # filter를 이용하여 로그인 한 유저와 연결되어 있는 캐릭터 객체가 있는지 찾음
        if Character.objects.filter(user=request.user).count() == 0:
            if request.method == 'POST':
                character_form = CharacterForm(request.POST)
                character_form = character_form.save(commit=False)
                character_form.user = request.user
                character_form.save()
                return redirect('games:adventure_home')
            else:
                character_form = CharacterForm()
            context = {
                'character_form': character_form,
            }
            return render(request, 'games/character_form.html', context)
        # 생성한 캐릭터가 있는 경우
        else:
            character = get_object_or_404(Character, user=request.user)
            # 무기를 얻지 못한 경우
            if character.weapon == None:
                # 무기 랜덤 선택
                # order_by('?')를 이용하여 랜덤하게 정렬 후 첫번째 항목을 가져옴
                random_weapon = Weapon.objects.order_by('?')[0]
                context = {
                    'random_weapon': random_weapon,
                }
                return render(request, 'games/adventure_new.html', context)
            # 무기를 얻은 경우
            else:
                context = {
                    'character': character,
                }
                return render(request, 'games/adventure_home.html', context)
    # 로그인 하지 않은 경우
    else:
        return redirect('accounts:login')

def weapon_get(request):
    if request.method == 'POST':
        character = get_object_or_404(Character, user=request.user)

        weapon_id = request.POST.get('random-weapon')
        selected_weapon = get_object_or_404(Weapon, id=weapon_id)
        
        character.weapon = selected_weapon
        character.save()
    return redirect('games:adventure_home')

# 모험 떠나기
def adventure_attack(request):
    # 랜덤 적 생성
    random_enemy = Enemy.objects.order_by('?')[0]
    
    context = {
        'random_enemy': random_enemy,
    }
    return render(request, 'games/adventure_attack.html', context)

def adventure_attack_result(request):
    if request.method == 'POST':
        # 로그인 한 유저의 캐릭터
        character = get_object_or_404(Character, user=request.user)

        # 캐릭터와 마주친 랜덤 적
        enemy_id = request.POST.get('random-enemy')
        enemy = get_object_or_404(Enemy, id=enemy_id)

        # [미션] 자유롭게 코드 작성
        # [미션] 필요 시 context 작성 후 html 페이지에 전달
        if character.weapon.power*10 >= enemy.hp:
            result = '승리'
            reward_coin = randint(enemy.hp*10-5, enemy.hp*10+5)
            character.coin += reward_coin
            character.save()
        else:
            result = '패배'
            reward_coin = 0
        
        context = {
            'enemy': enemy,
            'result': result,
            'reward_coin' : reward_coin,
        }
        return render(request, 'games/adventure_attack_result.html', context)
    return render(request, 'games/adventure_attack.html', context)

# 무기 공방
def weapon_workroom(request):
    character = get_object_or_404(Character, user=request.user)

    context = {
        'character': character,
        'weapon_name': character.weapon.name,
        'weapon_power': character.weapon.power,
    }
    return render(request, 'games/weapon_workroom.html', context)

# [미션] 자유롭게 코드 작성
# [미션] 무기 뽑기, 교체 등의 기능을 가진 함수 구현
def weapon_pick(request):
    if request.method == 'POST':
        character = get_object_or_404(Character, user=request.user)
        # 캐릭터가 갖고 있는 코인 저장
        character_coin = character.coin
        
        # 캐릭터가 500코인 이상 갖고 있는 경우
        if character_coin >= 500:
            # 500코인 소모
            character.coin = character_coin - 500
            character.save()

            random_weapon = Weapon.objects.order_by('?')[0]

            context = {
                'character': character,
                'weapon_name': character.weapon.name,
                'weapon_power': character.weapon.power,
                'random_weapon': random_weapon,
            }
            return render(request, 'games/weapon_change.html', context)
    return redirect('games:weapon_workroom')

def weapon_change(request):
    if request.method == 'POST':
        character = get_object_or_404(Character, user=request.user)

        # 랜덤으로 선택된 무기 id 가져오기
        weapon_id = request.POST.get('random-weapon')
        selected_weapon = get_object_or_404(Weapon, id=weapon_id)

        # 캐릭터에 새 무기 장착
        character.weapon = selected_weapon
        character.save()

        return redirect('games:weapon_workroom')
    return redirect('games:weapon_pick')

# 무기 공방
def weapon_workroom(request):
    character = get_object_or_404(Character, user=request.user)

    context = {
        'character': character,
        'weapon_name': character.weapon.name,
        'weapon_power': character.weapon.power,
    }
    return render(request, 'games/weapon_workroom.html', context)

# [미션] 자유롭게 코드 작성
# [미션] 무기 뽑기, 교체 등의 기능을 가진 함수 구현

games/templates/games/adventure_attack.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <div class="adventure">
    <h1>모험을 떠났습니다.</h1>
    <p>당신은 '{{random_enemy.name}}'을(를) 만났습니다.</p>
    
    <p>
      <!-- 공격하기 버튼을 누르면 game 앱의 adventure_attack_result url로 이동 -->
      <form action="{% url 'games:adventure_attack_result' %}" method="post">
        {% csrf_token %}
        <!-- value 값으로 랜덤 적의 id를 전달 -->
        <button type="submit" name="random-enemy" value="{{random_enemy.id}}">공격하기</button>
      </form>
    </p>
  
    <!-- [미션] 자유롭게 코드 작성 -->
    <p>
      <a href="{% url 'games:adventure_home' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">도망치기</a>
    </p>
  </div>
{% endblock %}

games/templates/games/adventure_attack_result.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <div class="adventure">
    <h1>전투 결과</h1>

    <!-- [미션] 자유롭게 코드 작성 -->
    <p>당신은 '{{enemy.name}}'와(과)의 전투에서 {{result}}하였습니다.</p>
  
    {% if result == "승리" %}
      <p>{{reward_coin}}코인을 획득하셨습니다.</p>
    {% endif %}
    <p>
      <a href="{% url 'games:adventure_attack' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">모험 떠나기</a>
    </p>
    <p>
      <a href="{% url 'games:adventure_home' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">돌아가기</a>
    </p>
  </div>
{% endblock %}

games/templates/games/adventure_home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
{% endblock %}

{% block body %}
  <div class="adventure">
    <h1>{{character.nickname}}님, 모험을 떠나보세요!</h1>

    <p>당신은 <<{{character.weapon.name}}>> 무기를 갖고 있습니다.</p>
    <p><<{{character.weapon.name}}>>의 공격력은 {{character.weapon.power}}입니다.</p>

    <p>
      <a href="{% url 'games:adventure_attack' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">모험 떠나기</a>
    </p>
    <p>
      <a href="{% url 'games:weapon_workroom' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">무기 공방</a>
    </p>
    <p>
      <a href="{% url 'games:game_list' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">돌아가기</a>
    </p>
  </div>
{% endblock %}

games/templates/games/adventure_new.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>{{user.character.nickname}}님의 모험을 시작합니다.</h1>

  <p>모험에 필요한 무기는 랜덤으로 선택됩니다.</p>
  <p><<{{random_weapon.name}}>> 무기가 선택되었습니다.</p>
  <form action="{% url 'games:weapon_get' %}" method="post">
    {% csrf_token %}
    <button type="submit" name="random-weapon" value="{{random_weapon.id}}">무기 받기</button>
  </form>
{% endblock %}

games/templates/games/character_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
{% endblock %}

{% block body %}
  <h1>캐릭터 생성</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      {{character_form}}
      <input type="submit" value="생성">
    </div>
  </form>
{% endblock %}

games/templates/games/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_list.css' %}">
{% endblock %}

{% block body %}
  <h1>게임 목록</h1>

  <ol>
    <p><a href="{% url 'games:rsp_select'%}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">가위바위보 게임</a></p>
    <p><a href="{% url 'games:weapon_list'%}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">무기 목록</a></p>
    <p><a href="{% url 'games:adventure_home'%}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">장고캣의 모험(가제)</a></p>
  </ol>
{% endblock %}

games/templates/games/rsp_result.html
{% extends 'games/rsp_select.html' %}
{% load static %}

{% block rsp_head %}
  <link rel="stylesheet" href="{% static 'css/games/rsp_result.css' %}">
{% endblock %}

{% block rsp_body %}
  <h1>가위바위보 게임 결과</h1>
  
  <p>나는 <b>{{pick}}</b>를 선택했습니다.</p>
  <p>컴퓨터는 <b>{{com}}</b>를 선택했습니다.</p>

  <h2 class="rsp__result">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

games/templates/games/rsp_select.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/rsp_select.css' %}">
  {% block rsp_head %}
  {% endblock %}
{% endblock %}

{% block body %}

  {% block rsp_body %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="rsp__count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'games:rsp_reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp__button">
    <button on_click="location.href({% url 'games:rsp_result' '가위' %})">가위</a>
    <button on_click="location.href({% url 'games:rsp_result' '바위' %})">바위</a>
    <button on_click="location.href({% url 'games:rsp_result' '보' %})">보</a>
  </div>
  
{% endblock %}

games/templates/games/weapon_change.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 뽑기 결과</h1>

  <hr>
  <p>{{character.nickname}}님의 보유 현황</p>
  <p>
    <ul>
      <li><p>보유 무기 : <span id="weapon__name">{{weapon_name}}</span>&nbsp;(공격력 : +{{weapon_power}})</p></li>
      <li><p>보유 코인 : {{character.coin}}코인</p></li>
    </ul>
  </p>
  <hr>

  <p>당신이 뽑은 무기는 <<{{random_weapon.name}}>>입니다.</p>
  <p>교체하시겠습니까?</p>

  <p>
    <form action="{% url 'games:weapon_change' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="random-weapon" value="{{random_weapon.id}}" onclick="alertSuccess()">교체하기</button>
      <span class="weapon-info">(※ 무기 레벨이 초기화됩니다.)</span>
    </form>
  </p>

  <p>
    <form action="{% url 'games:weapon_pick' %}" method="post" onsubmit="return checkPick()">
      {% csrf_token %}
      {% if character.coin < 500 %}
        <button type="submit" class="disabled" disabled>무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% else %}
        <button type="submit">무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 무기를 교체하면 무기 레벨이 초기화됩니다.)</span>
      {% endif %}
    </form>
  </p>

  <p>
    <button onclick="goBack()">돌아가기</button>
  </p>

  <script>
    function alertSuccess() {
      alert('교체되었습니다.');
    }

    function checkPick() {
      const result = confirm("정말 뽑으시겠습니까?\n500코인이 소모됩니다.");
      return result;
    }

    function goBack() {
      const url = "{% url 'games:weapon_workroom' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/weapon_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/weapon_form.css' %}">
{% endblock %}

{% block body %}
  <h1>무기 생성</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      {{weapon_form.as_p}}
      <input type="submit" value="무기 생성">
    </div>
  </form>
{% endblock %}

games/templates/games/weapon_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/weapon_list.css' %}">
{% endblock %}

{% block body %}
  <h1>전체 무기 목록</h1>

  <ul>
    {% for weapon in weapons %}
      <li><p>{{weapon.name}} (공격력: {{weapon.power}})</p></li>
    {% empty %}
      <li><p>무기가 없습니다.</p></li>
    {% endfor %}
    <a class="button" href="{% url 'games:weapon_create' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">무기 생성하기</a>
  </ul>
{% endblock %}

games/templates/games/weapon_workroom.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 공방</h1>
  
  <hr>
  <p>{{character.nickname}}님의 보유 현황</p>
  <p>
    <ul>
      <li><p>보유 무기 : <span id="weapon__name">{{weapon_name}}</span>&nbsp;(공격력 : +{{weapon_power}})</p></li>
      <li><p>보유 코인 : {{character.coin}}코인</p></li>
    </ul>
  </p>
  <hr>
  
  <!-- [미션] 자유롭게 코드 작성 -->
  <p>
    <form action="{% url 'games:weapon_pick' %}" method="post" onsubmit="return checkPick()">
      {% csrf_token %}
      {% if character.coin < 500 %}
        <button type="submit" class="disabled" disabled>무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% else %}
        <button type="submit">무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 무기를 교체하면 무기 레벨이 초기화됩니다.)</span>
      {% endif %}
    </form>
  </p>
  
  <p>
    <a href="{% url 'games:adventure_home' %}" style="display: inline-block; padding: 5px 10px; border: 1px solid; border-radius: 10px; background-color: Khaki; color: SaddleBrown; font-size: 1rem; text-decoration: none;">돌아가기</a>
  </p>

  <script>
    function checkPick() {
      {% if character.coin < 500 %}
        alert("코인이 부족합니다");
        return false;
      {% else %}
        const result = confirm("정말 뽑으시겠습니까?\n500코인이 소모됩니다.");
        return result;
      {% endif %}
    }
  </script>
{% endblock %}