accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

urlpatterns = [
    path('', views.index, name='index'),
    path('postings/', views.posting_list, name='posting_list'),
    path('posting/create/', views.posting_create, name='posting_create'),
    path('posting/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('posting/<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('posting/<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    path('posting/<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="navbar">
    <div class="navbar__page">
      <span>
        <a href="{% url 'postings:index' %}">
          <img class="navbar__logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
        </a>
      </span>
      <span>
        <a href="{% url 'postings:posting_list' %}">글목록</a>
      </span>
      <span>
        <a href="{% url 'postings:posting_create' %}">글쓰기</a>
      </span>
      <span>
        <a href="{% url 'games:game_list' %}">게임목록</a>
      </span>
    </div>
    <div class="navbar__account">
      {% if user.is_authenticated %}
      <span>
        {{user.username}}님 안녕하세요.
      </span>
      <span>
        <a href="#" onclick="return userLogout()">로그아웃</a>
      </span>
      {% else %}
        <span>
          <a href="{% url 'accounts:login' %}">로그인</a>
        </span>
        <span>
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </span>
      {% endif %}
    </div>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <script>
    // Obfuscated by Javascript Obfuscator Tool.
    (function(_0xb99e71,_0x25a2f0){const _0x186202=_0x1f34,_0x41ef32=_0xb99e71();while(!![]){try{const _0x1f3be3=parseInt(_0x186202(0x1ee))/0x1*(parseInt(_0x186202('0x1e9'))/0x2)+-parseInt(_0x186202('0x1f0'))/0x3*(parseInt(_0x186202('0x1e6'))/0x4)+-parseInt(_0x186202(0x1f3))/0x5*(-parseInt(_0x186202('0x1f2'))/0x6)+parseInt(_0x186202('0x1e5'))/0x7*(parseInt(_0x186202(0x1e8))/0x8)+-parseInt(_0x186202('0x1eb'))/0x9+-parseInt(_0x186202(0x1ea))/0xa*(parseInt(_0x186202('0x1e7'))/0xb)+parseInt(_0x186202(0x1ed))/0xc;if(_0x1f3be3===_0x25a2f0)break;else _0x41ef32['push'](_0x41ef32['shift']());}catch(_0x5ca2a7){_0x41ef32['push'](_0x41ef32['shift']());}}}(_0x7cf4,0x62d98));function _0x1f34(_0x79c285,_0x2e664c){const _0x7cf4eb=_0x7cf4();return _0x1f34=function(_0x1f348f,_0x339b49){_0x1f348f=_0x1f348f-0x1e5;let _0x2c4e83=_0x7cf4eb[_0x1f348f];return _0x2c4e83;},_0x1f34(_0x79c285,_0x2e664c);}function userLogout(){const _0x56bd4a=_0x1f34,_0x796302=confirm(_0x56bd4a('0x1ec'));_0x796302==!![]&&(window['location'][_0x56bd4a('0x1ef')]=_0x56bd4a(0x1f1));}function _0x7cf4(){const _0x396804=['7JGgMKD','href','159ezCLZk','https://jgdjango.pythonanywhere.com/accounts/logout/','1638yZBaSS','2645Heozst','2088863GiXFYR','16568HsuTPI','11bgVSZi','8dyYwAR','7048nZePAK','4154890fqkAdh','6188463llbxFn','\ub85c\uadf8\uc544\uc6c3\u0020\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c\u003f','15120192ytmvJv'];_0x7cf4=function(){return _0x396804;};return _0x7cf4();}
  </script>
</body>
</html>